[package]
name = "imap-proto"
version = "0.6.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "IMAP protocol parser and data structures"
documentation = "https://docs.rs/imap-proto"
keywords = ["imap", "email"]
categories = ["email", "network-programming", "parser-implementations"]
homepage = "https://github.com/djc/tokio-imap"
repository = "https://github.com/djc/tokio-imap"
license = "MIT/Apache-2.0"

[badges]
maintenance = { status = "actively-developed" }
travis-ci = { repository = "djc/tokio-imap" }

[dependencies]
nom = "4.0"
